<?php

/**
 * @file
 * Contains pass_js.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pass_js_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pass_js module.
    case 'help.page.pass_js':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pass js vaiable from controller.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pass_js_theme() {
  return [
    'pass_js' => [
      'render element' => 'children',
    ],
  ];
}
